name: release-github-action

on:
  push:
    branches:
      - dev
    paths:
      - "github/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  release:
    if: github.repository == 'SymbolicOS/symbolic' && (vars.ENABLE_EXTENSION_PUBLISH == 'true')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Release
        run: |
          git config --global user.email "bot@symbolic.computer"
          git config --global user.name "symbolic"
          ./github/script/release
